sudo: false
language: node_js
matrix:
  include:
    - node_js: 10
      script: 'npm run test-node:ci'
      before_install:
        - git config --global url."https://github.com/".insteadOf "git://github.com/"
    - node_js: node
      addons:
        sauce_connect: true
      before_script:
        - npm run http-server &
        - sleep 2
      script: npm run ui
# grunt-esnext works with later grunt but has a peer dep for earlier
install:
  - npm install --legacy-peer-deps

dist: focal
services:
  - xvfb
